[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--verbose",
    "--tb=short",
    "--maxfail=10"
]
markers = [
    "smoke: marks tests as smoke tests",
    "regression: marks tests as regression tests",
    "critical: marks tests as critical tests"
]